version: '3.9'

services:
  openquake-engine:
    image: openquake/engine:LTS
    ports:
      - 8800:8800
    env_file:
      - ./.env.dev
    # volumes:
    #   - ./openquake/server/local_settings.py:/home/openquake/local_settings.py:ro
