version: '3.9'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx-proxy/etc/nginx/conf.d/global.conf:/etc/nginx/conf.d/global.conf:ro
    depends_on:
      - openquake-engine
  letsencrypt:
    image: nginxproxy/acme-companion:latest
    restart: always
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy
  openquake-engine:
    # image: openquake/engine:LTS
    image: openquake/engine:3.16
    # restart: always # uncomment to start container on server boot
    # ports:
    #   - 8800:8800 # openquake/engine by default EXPOSEs 8800
    env_file:
      - ./.env.prod
    volumes:
      - ./openquake/server/local_settings.py:/home/openquake/local_settings.py:ro # django webui overrides

volumes:
  html:
  vhost:
  certs:
  acme:
