version: '3.9'

services:
  openquake-engine:
    # image: openquake/engine:LTS
    image: openquake/engine:3.16
    ports:
      - 8800:8800
    env_file:
      - ./.env.dev
    # volumes:
    #   - ./openquake/openquake.cfg:/opt/openquake/openquake.cfg:ro
    #   - ./openquake/server/local_settings.py:/home/openquake/local_settings.py:ro
